/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SetUserOptFrame.java
 *
 * Created on 2008-12-11, 17:56:18
 */

package com.ufc.uif.qh3.acad.ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.ComboBoxEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.text.JTextComponent;

import org.dom4j.Element;
import com.ufc.uif.base_adaptor.AdaptorWriter;
import com.ufc.uif.base_adaptor.busioperator.BusiOperationException;
import com.ufc.uif.qh3.acad.operation.JAutoCompleteComboBox;
import com.ufc.uif.qh3.acad.operation.SetUserSessionInfo;
import com.ufc.uif.tccommunicationimpl.operation.connecttc.TCUtil;
import com.ufc.uif.tcuacommunication.objects.WSObject;
import com.ufc.uif.tcuacommunication.operation.OperationManagerFactory;
import com.ufc.uif.tcuacommunication.operation.exception.TCOperationException;

/**
 * 
 * @author Administrator
 */
public class SetUserOptDialog extends _UIFDialog {

  private AdaptorWriter out;
  private String[] sortProjects;
  private String[] projectInfos;

  private static final long serialVersionUID = 1L;

  /** Creates new form SetUserOptFrame */
  public SetUserOptDialog(OperationManagerFactory factory) {
    super(factory);
    setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    addWindowListener(new WindowAdapter() {
      public void windowClosing(WindowEvent e) {
        try {
          out.setFuncID("SetUserOpt");
          out.setResult("false");
          out.setDesc("用户取消。");
          out.sendResultToUI();
        } catch (IOException ex) {
          ex.printStackTrace();
        }
        dispose();
      }
    });
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */

  public void initComponents() {
    System.out.println("-----------------initComponents------------------");
    jPanel3 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jCombo_role = new javax.swing.JComboBox();
    jLabel2 = new javax.swing.JLabel();
    jCombo_group = new javax.swing.JComboBox();
    jLabel3 = new javax.swing.JLabel();
    jCombo_project = new javax.swing.JComboBox();
    // jCombo_project = new JAutoCompleteComboBox();
    jPanel2 = new javax.swing.JPanel();
    jBtn_OK = new javax.swing.JButton();
    jBtn_Cancel = new javax.swing.JButton();

    setTitle("用户会话设置");

    setAlwaysOnTop(true);

    setPreferredSize(new Dimension(550, 245));

    jPanel3.setBackground(new java.awt.Color(226, 245, 252));
    jPanel3.setName("jPanel3"); // NOI18N

    jPanel1.setBackground(new java.awt.Color(241, 250, 255));
    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "用户会话设置", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
        new java.awt.Font("宋体", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
    jPanel1.setName("jPanel1"); // NOI18N

    jLabel1.setText("角色");
    jLabel1.setName("jLabel1"); // NOI18N

    jCombo_group.setName("jCombo_group"); // NOI18N
    jCombo_group.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jCombo_groupItemStateChanged(evt);
      }
    });

    jLabel2.setText("组");
    jLabel2.setName("jLabel2"); // NOI18N

    jCombo_role.setName("jCombo_role"); // NOI18N

    jLabel3.setText("项目");
    jLabel3.setName("jLabel3"); // NOI18N

    jCombo_project.setName("jCombo_project"); // NOI18N

    org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
        jPanel1Layout
            .createSequentialGroup()
            .add(49, 49, 49)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING).add(jLabel2).add(jLabel1).add(jLabel3))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING).add(org.jdesktop.layout.GroupLayout.LEADING, jCombo_project, 0, 170, Short.MAX_VALUE)
                .add(jCombo_role, 0, 170, Short.MAX_VALUE).add(jCombo_group, 0, 170, Short.MAX_VALUE)).add(44, 44, 44)));
    jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
        jPanel1Layout
            .createSequentialGroup()
            .addContainerGap()
            .add(jPanel1Layout
                .createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1Layout.createSequentialGroup().add(43, 43, 43)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jCombo_role).add(jLabel1)).add(18, 18, 18)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jCombo_project).add(jLabel3)))
                .add(jPanel1Layout.createSequentialGroup().add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jCombo_group).add(jLabel2))
                    .add(82, 82, 82))).addContainerGap()));

    jPanel2.setBackground(new java.awt.Color(226, 245, 252));
    jPanel2.setName("jPanel2"); // NOI18N

    jBtn_OK.setText("确定");
    jBtn_OK.setName("jBtn_OK"); // NOI18N
    jBtn_OK.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtn_OKActionPerformed();
      }
    });

    jBtn_Cancel.setText("取消");
    jBtn_Cancel.setName("jBtn_Cancel"); // NOI18N
    jBtn_Cancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtn_CancelActionPerformed();
      }
    });

    org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(org.jdesktop.layout.GroupLayout.TRAILING,
        jPanel2Layout.createSequentialGroup().addContainerGap(167, Short.MAX_VALUE).add(jBtn_OK).add(18, 18, 18).add(jBtn_Cancel).addContainerGap()));
    jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
        jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jBtn_Cancel).add(jBtn_OK)));

    org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
        jPanel3Layout
            .createSequentialGroup()
            .addContainerGap()
            .add(jPanel3Layout
                .createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel3Layout.createSequentialGroup().add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(2, 2, 2)).add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addContainerGap()));
    jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
        jPanel3Layout.createSequentialGroup().addContainerGap().add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap()));

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

    pack();
  }// </editor-fold>

  /**
   * 在ComboBox中键入值时，自动筛选出符合输入的选项
   * 
   * @author Liugz
   * @create on 2009-8-11 This project for CAD_Concrete
   * @param e
   */
  protected void filterComboBoxItems() {
    // Object obj = e.getSource();
    // if(obj instanceof ComboBoxEditor){
    // JComboBox combo = (JComboBox)obj;
    // ComboBoxEditor comboEditor = (ComboBoxEditor)obj;
    ComboBoxEditor comboEditor = (ComboBoxEditor) jCombo_project.getEditor();
    // 获取输入的值
    String insertValue = ((JTextComponent) comboEditor.getEditorComponent()).getText();
    // String txtValue = combo.getSelectedItem().toString();
    /*
     * // 获取该ComboBox中的所有值 String[] items = new
     * String[combo.getItemCount()]; for (int i = 0; i <
     * combo.getItemCount(); i++) { items[i] =
     * Util.convertNull(combo.getItemAt(i)); }
     */
    // 筛选
    List<String> filteredItems = new ArrayList<String>(projectInfos.length);
    for (int i = 0; i < projectInfos.length; i++) {
      if (projectInfos[i].contains(insertValue)) {
        filteredItems.add(projectInfos[i]);
      }
    }
    // 将筛选出的值，加入到ComboBox中
    jCombo_project.removeAllItems();
    for (int i = 0; i < filteredItems.size(); i++) {
      jCombo_project.addItem(filteredItems.get(i));
    }
    // }
  }

  private void jBtn_OKActionPerformed() {

    String group = (String) jCombo_group.getSelectedItem();
    String role = (String) jCombo_role.getSelectedItem();
    String project = (String) jCombo_project.getSelectedItem();
    String projectName = project.split(" - ")[1];
    SetUserSessionInfo info = new SetUserSessionInfo();
    Map<String, String> input = new HashMap<String, String>();
    input.put("group", group);
    input.put("role", role);
    input.put("project", projectName);
    info.setSessionInfo(input);
    dispose();
    try {
      out.setFuncID("SetUserOpt");
      out.setResult("true");
      out.setDesc("");
      out.sendResultToUI();
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  private void jBtn_CancelActionPerformed() {
    // TODO add your handling code here:
    dispose();
    try {
      out.setFuncID("SetUserOpt");
      out.setResult("false");
      out.setDesc("");
      out.sendResultToUI();
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  private void jCombo_groupItemStateChanged(java.awt.event.ItemEvent evt) {
    String group = (String) evt.getItem();
    jCombo_role.removeAllItems();
    List<String> rolelist = avilable.get(group);
    String[] roles = rolelist.toArray(new String[rolelist.size()]);
    jCombo_role.setModel(new DefaultComboBoxModel(roles));
  }

  // Variables declaration - do not modify
  private javax.swing.JButton jBtn_Cancel;
  private javax.swing.JButton jBtn_OK;
  private javax.swing.JComboBox jCombo_group;
  private javax.swing.JComboBox jCombo_project;
  private javax.swing.JComboBox jCombo_role;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  // End of variables declaration//GEN-END:variables
  Map<String, List<String>> avilable = null;

  @Override
  public void initConfig() {
    // TODO Auto-generated method stub
  }

  @Override
  public void initListener() {
    // TODO Auto-generated method stub

  }

  private void initDialog() {
    
    System.out.println("-----------------initDialog------------------");
    jCombo_group.removeAllItems();
    jCombo_role.removeAllItems();
    jCombo_project.removeAllItems();
    SetUserSessionInfo info = new SetUserSessionInfo();
    Map<String, String> sessioninfo = info.getSessionInfo();
    avilable = info.getAvilableGroupRoleInfo();

    String[] groups = avilable.keySet().toArray(new String[avilable.keySet().size()]);
    // String[] projects=info.getAssignableprojects();
    projectInfos = null;
    sortProjects = null;
    try {
      WSObject[] projs = TCUtil.getProjectsOfUser();
    
      if (projs != null && projs.length > 0) {
        System.out.println("项目个数="+projs.length);
      }
      if (null != projs && projs.length != 0) {
        projectInfos = new String[projs.length];
        for (int i = 0; i < projs.length; i++) {
          projectInfos[i] = projs[i].getId() + " - " + projs[i].getName();
        }
      } else {
        projectInfos = new String[1];
        projectInfos[0] = "";
      }
      // sortProjects = sortProjectName(projectInfos);
      sortProjects = projectInfos;
    } catch (TCOperationException e) {
      e.printStackTrace();
    }
    // jGroupComboBox.setModel(new
    // javax.swing.DefaultComboBoxModel(groups));
    for (int i = 0; i < groups.length; i++) {
      jCombo_group.addItem(groups[i]);
      // System.out.println(groups[i]);
    }
    List<String> rolelist = avilable.get(sessioninfo.get("group"));
    String[] roles = rolelist.toArray(new String[rolelist.size()]);
    jCombo_role.setModel(new DefaultComboBoxModel(roles));

    jCombo_group.setSelectedItem((String) sessioninfo.get("group"));
    jCombo_role.setSelectedItem(sessioninfo.get("role"));

    // 显示默认项目信息
    DefaultComboBoxModel jComboProjModel = new DefaultComboBoxModel(sortProjects);
    jCombo_project.setModel(jComboProjModel);
    jCombo_project.insertItemAt("", 0);
    String defaultProj = sessioninfo.get("project");
    for (String str : sortProjects) {
      if (str.contains(defaultProj)) {
        jCombo_project.setSelectedItem(str);
      }
    }
    // 项目栏变为可自动筛选
    jCombo_project.setEditable(true);
    new JAutoCompleteComboBox(jCombo_project);
    // new AutoCompletion(jCombo_project);
    pack();
  }

  /*  *//**
   * 按照项目名称排序 泵车 拖泵 车载泵
   * 
   * @author Liugz
   * @create on 2009-6-24 This project for CAD_Concrete
   * @param projects
   */
  /*
   * private String[] sortProjectName(String[] projects) { // String[] names =
   * new String[projects.length]; List<String> sortNames = new
   * ArrayList<String>(); List<String> sortNames2 = new ArrayList<String>();
   * for (int i = 0; i < projects.length; i++) { String proj = projects[i];
   * if(proj.contains("泵车")){ sortNames.add(proj); } else
   * if(proj.contains("拖泵")){ sortNames.add(proj); } else
   * if(proj.contains("车载泵")){ sortNames.add(proj); } else{
   * sortNames2.add(proj); } } sortNames.addAll(sortNames2); return
   * sortNames.toArray(new String[0]); }
   */

  @Override
  public void doOperation(Element requestBody, AdaptorWriter out) throws BusiOperationException {
    this.requestBody = requestBody;
    this.out = out;
    
    System.out.println("-----------------doOperation------------------");
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    Dimension frameSize = getSize();
    if (frameSize.height > screenSize.height) {
      frameSize.height = screenSize.height;
    }
    if (frameSize.width > screenSize.width) {
      frameSize.width = screenSize.width;
    }
    setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
    setSize(frameSize.width, frameSize.height - 30);

    initDialog();
    setVisible(true);
  }
}
