package com.ufc.uif.qh3.acad.drawing;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.table.TableRowSorter;
import javax.swing.text.JTextComponent;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

import org.dom4j.Element;

import com.ufc.uif.base_adaptor.AdaptorWriter;
import com.ufc.uif.qh3.acad.operation.ParseRequestXML;
import com.ufc.uif.qh3.acad.ui.StateDialog;
import com.ufc.uif.qh3.acad.ui.WaitDialog;
import com.ufc.uif.qh3.acad.ui.WorkspaceTableRender;
//import com.ufc.uif.tcuacommunication.objects.ClassifiAttribute;
//import com.ufc.uif.tcuacommunication.objects.ClassifiClass;
//import com.ufc.uif.tcuacommunication.objects.ClassifiObject;
import com.ufc.uif.tccommunicationimpl.object.ClassifiAttribute;
import com.ufc.uif.tccommunicationimpl.object.ClassifiClass;
import com.ufc.uif.tccommunicationimpl.object.ClassifiObject;
import com.ufc.uif.tccommunicationimpl.operation.TCClassificationOperation;
import com.ufc.uif.tcuacommunication.objects.LOVsValue;
import com.ufc.uif.tcuacommunication.objects.WSObject;
//import com.ufc.uif.tcuacommunication.operation.ITCClassificationOperation;
import com.ufc.uif.tcuacommunication.operation.ITCTCObjOperation;
import com.ufc.uif.tcuacommunication.operation.exception.TCOperationException;
import com.ufc.uif.util.service.ServiceUtil;

/**
 *
 * @author Wangjinfei
 */
public class QueryMatPane extends javax.swing.JPanel {

  private static final long serialVersionUID = -3634956687688133397L;

  /** Creates new form ClassificationFrame */

    public QueryMatPane(JFrame frame) {
//      super(frame, "Classification", true);
      this.frame = frame;
        initDialog();
    }

    public QueryMatPane() {

        initDialog();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        treePanel = new javax.swing.JScrollPane();
        classifiObjTree = new javax.swing.JTree();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        attribsPanel = new javax.swing.JScrollPane();
        attribPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        clsBtn = new javax.swing.JButton();
        schBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tablePanel = new javax.swing.JScrollPane();
        wsObjTable = new javax.swing.JTable();
        buttonPanel1 = new javax.swing.JPanel();
        cancelBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(226, 245, 252));

        jSplitPane1.setName("jSplitPane1"); // NOI18N
        jSplitPane1.setOneTouchExpandable(true);
        jSplitPane1.setDividerLocation(210);

        jPanel1.setBackground(new java.awt.Color(226, 245, 252));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new Dimension(190, 600));

        treePanel.setBackground(new java.awt.Color(241, 250, 255));
        treePanel.setName("treePanel"); // NOI18N
        classifiObjTree.addTreeSelectionListener(new TreeSelectionListener(){
          public void valueChanged(TreeSelectionEvent event) {
            treeSelectionAction(event);
          }
        });

        classifiObjTree.setBackground(new java.awt.Color(241, 250, 255));
        classifiObjTree.setName("classifiObjTree"); // NOI18N
        treePanel.setViewportView(classifiObjTree);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(treePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(treePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setName("jSplitPane2"); // NOI18N
        jSplitPane2.setDividerLocation(210);

        jPanel2.setBackground(new java.awt.Color(226, 245, 252));
        jPanel2.setName("jPanel2"); // NOI18N

        attribsPanel.setBackground(new java.awt.Color(226, 245, 252));
        attribsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("分类搜索条件"));
        attribsPanel.setAutoscrolls(true);
        attribsPanel.setName("attribsPanel"); // NOI18N
        attribsPanel.setOpaque(false);

        attribPanel.setBackground(new java.awt.Color(241, 250, 255));
        attribPanel.setName("attribPanel"); // NOI18N
//        attribPanel.setLayout(new java.awt.GridLayout(2, 2));
        attribsPanel.setViewportView(attribPanel);

        buttonPanel.setBackground(new java.awt.Color(226, 245, 252));
        buttonPanel.setName("buttonPanel"); // NOI18N

        clsBtn.setText("清除");
        clsBtn.setName("clsBtn"); // NOI18N
        clsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clsBtnActionPerformed(evt);
            }
        });

        schBtn.setText("搜索");
        schBtn.setName("schBtn"); // NOI18N
        schBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout buttonPanelLayout = new org.jdesktop.layout.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(406, Short.MAX_VALUE)
                .add(schBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(clsBtn)
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(buttonPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(clsBtn)
                .add(schBtn))
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(attribsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .add(buttonPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(attribsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(buttonPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane2.setTopComponent(jPanel2);

        jPanel3.setBackground(new java.awt.Color(226, 245, 252));
        jPanel3.setName("jPanel3"); // NOI18N

        jPanel4.setBackground(new java.awt.Color(226, 245, 252));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("分类对象"));
        jPanel4.setName("jPanel4"); // NOI18N

        tablePanel.setBackground(new java.awt.Color(241, 250, 255));
        tablePanel.setAutoscrolls(true);
        tablePanel.setName("tablePanel"); // NOI18N

        wsObjTable.setBackground(new java.awt.Color(241, 250, 255));
        wsObjTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        wsObjTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        wsObjTable.setName("wsObjTable"); // NOI18N
        tablePanel.setViewportView(wsObjTable);

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tablePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tablePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );

        buttonPanel1.setBackground(new java.awt.Color(226, 245, 252));
        buttonPanel1.setName("buttonPanel1"); // NOI18N

        cancelBtn.setText("关闭");
        cancelBtn.setName("cancelBtn"); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }

        });

        okBtn.setText("确定");
        okBtn.setName("okBtn"); // NOI18N
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }

        });

        org.jdesktop.layout.GroupLayout buttonPanel1Layout = new org.jdesktop.layout.GroupLayout(buttonPanel1);
        buttonPanel1.setLayout(buttonPanel1Layout);
        buttonPanel1Layout.setHorizontalGroup(
            buttonPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, buttonPanel1Layout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .add(okBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(cancelBtn)
                .addContainerGap())
        );
        buttonPanel1Layout.setVerticalGroup(
            buttonPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(buttonPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(cancelBtn)
                .add(okBtn))
        );

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(buttonPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(buttonPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane2.setRightComponent(jPanel3);

        jSplitPane1.setRightComponent(jSplitPane2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

    }// </editor-fold>

  /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ClassificationFrame().setVisible(true);
//            }
//        });
//      ClassificationFrame frame = new ClassificationFrame(null);
//      frame.initDialog();

    }

    // Variables declaration - do not modify
    private javax.swing.JPanel attribPanel;
    private javax.swing.JScrollPane attribsPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel buttonPanel1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTree classifiObjTree;
    private javax.swing.JButton clsBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JButton okBtn;
    private javax.swing.JButton schBtn;
    private javax.swing.JScrollPane tablePanel;
    private javax.swing.JScrollPane treePanel;
    private javax.swing.JTable wsObjTable;
   // private TCObjectOperation tcop = new TCObjectOperation();
    private ITCTCObjOperation tcop=  (ITCTCObjOperation)ServiceUtil.getService(ITCTCObjOperation.class.getName(), QueryMatPane.class.getClassLoader());
    // End of variables declaration

    private void clsBtnActionPerformed(ActionEvent evt) {
    // TODO Auto-generated method stub
      resetAttribPanel();
    clearTablePanel();
  }

  private void schBtnActionPerformed(ActionEvent evt) {
    Thread thread = new Thread(new Runnable(){
      public void run() {
        if(waitDlg != null)
          waitDlg.dispose();

        DefaultMutableTreeNode seleNode = (DefaultMutableTreeNode)classifiObjTree.getSelectionPath().getLastPathComponent();
        ClassifiClass clazz = (ClassifiClass)seleNode.getUserObject();
        String type = clazz.getType();
        int childcnt = clazz.getChildCount();
        /*if((!"StorageClass".equalsIgnoreCase(type) && !"SubClass".equalsIgnoreCase(type)) || childcnt != 0){
          JOptionPane.showMessageDialog(frame, "请选择叶子节点进行查询！", "提示", JOptionPane.INFORMATION_MESSAGE);
          return ;
        }*/

        waitDlg = new WaitDialog(frame, false);
        waitDlg.setMessage("正在进行操作，请稍候……");
        frame.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        queryClassificationObject();
        frame.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        waitDlg.dispose();
      }
    });
    thread.start();
  }

//  public void doOperation(Element requestBody, AdaptorWriter out)
//      throws BusiOperationException {
//    this.requestBody = requestBody;
//    this.out = out;
//    // LiugzTodo
//    initDialog();
//  }

  public void initDialog(){
      initComponents();
      initJTree();
    }

  /**
   * 关闭窗口
   *
   * @author Liugz
   * @create on 2008-12-22 This project for CYM
   */
  public void closeWindow() {
    try {
      out.setFuncID("QueryMat");
      out.setResult("CloseWindow");
      out.setDesc("用户取消操作。");
      out.sendResultToUI();
    } catch (IOException ex) {
      ex.printStackTrace();
    }
    frame.dispose();
  }

  /**
   * 初始化JTree
   * This project for CAD_Concrete
   */
  private void initJTree() {
    ClassifiTreeCellRender render = new ClassifiTreeCellRender();
    root = new DefaultMutableTreeNode("Classification Root");
    //root1 = new DefaultMutableTreeNode("材料库");
  
    //root.add(root1);
    
    List<ClassifiClass> subRoot = cfop.getClassificationRoot("ICM");
    if (cfop==null)
    {
      System.out.println("cfop 空值");
    }
    if  (subRoot==null)
    {
      System.out.println("subRoot 空值");
    }
    for(Iterator<ClassifiClass> itor = subRoot.iterator(); itor.hasNext();){
      ClassifiClass clClass = itor.next();
      DefaultMutableTreeNode node = new DefaultMutableTreeNode(clClass);
      if(node.getUserObject().toString().contains("材料")){
        
        root.add(node);
      }
    }
    
    treeModel = new DefaultTreeModel(root);
    classifiObjTree.setModel(treeModel);
    classifiObjTree.setCellRenderer(render);
//    classifiObjTree.setRootVisible(true);
    classifiObjTree.setExpandsSelectedPaths(true);
    classifiObjTree.setScrollsOnExpand(true);

    tableRender = new WorkspaceTableRender();
    wsObjTable.setDefaultRenderer(String.class, tableRender);

    // 设置attribPanel的布局管理器
//    attribPanel.setLayout(new BorderLayout());
  }

  /**
   * 点击树节点时，查询其子节点
   * @author Liugz
   * @create on 2009-3-4
   * This project for tc_communication.teamcenter2007
   */
  public void findSubNodes(){
    TreePath selecPath = classifiObjTree.getSelectionPath();
    DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode)classifiObjTree.getSelectionPath().getLastPathComponent();
    Object nodeObj = selectedNode.getUserObject();
    if(nodeObj instanceof ClassifiClass){
      ClassifiClass clazzNode = (ClassifiClass) nodeObj;
      if(clazzNode.getChildCount() > 0){ // (!"StorageClass".equalsIgnoreCase(clazzNode.getType()))
        selectedNode.removeAllChildren();
//        classifiObjTree.updateUI();
        List<ClassifiClass> subRoot = cfop.getClassificationRoot(clazzNode.getId());
        System.out.println("subRoot.size:"+subRoot.size());
        for(Iterator<ClassifiClass> itor = subRoot.iterator(); itor.hasNext();){
          ClassifiClass clClass = itor.next();
          DefaultMutableTreeNode node = new DefaultMutableTreeNode(clClass);
          selectedNode.add(node);
          System.out.println("add(node):"+node);
        }
      }
      //else {
      
        if(null != clazzNode.getAttributes() && clazzNode.getAttributes().length != 0){
          ClassifiAttribute[] attributes = clazzNode.getAttributes();
          // 设置搜索条件Panel
          int attribLen = attributes.length ;
          attribPanel.removeAll();
          // 设置搜索条件的布局
//            attribPanel.setLayout(new GridLayout(attribLen, 2, 2, 2));
          attribPanel.setLayout(new GridBagLayout());
          GridBagConstraints c = new GridBagConstraints();
          c.fill = GridBagConstraints.HORIZONTAL; // components grow in both dimensions
          c.insets = new Insets(5, 5, 5, 5); // 5-pixel margins on all sides
          
          for(int k = 0; k < attribLen; k++){
            ClassifiAttribute attrib = attributes[k];
            if(attrib.getFormatType() >= 0){ // JTextField类型
              c.gridx = 0;
              c.gridy = k;
              c.gridwidth = 1;
              c.gridheight = 1;
              JLabel label = new JLabel(attrib.getName());
              attribPanel.add(label, c);
              
              c.gridx = 1;
              c.gridy = k;
              c.gridwidth = 1;
              c.gridheight = 1;
              JTextField text = new JTextField();
              text.setPreferredSize(prefSize);
              attribPanel.add(text, c);
              text.setName(Integer.toString(attrib.getId()));
              
              c.gridx = 2;
              c.gridy = k;
              c.gridwidth = 1;
              c.gridheight = 1;
              JLabel label2 = new JLabel(attrib.getUnitName());
              attribPanel.add(label2, c);
            }
            else { // JComboBox类型
              c.gridx = 0;
              c.gridy = k;
              c.gridwidth = 1;
              c.gridheight = 1;
              JLabel label = new JLabel(attrib.getName());
              attribPanel.add(label, c);
              // 获取LOV值
              LOVsValue[] lovs = cfop.getLOVOfAttribute(attrib.getFormatLength());
              // 将值添加到ComboBox中
              JComboBox combo = new JComboBox(lovs);
              c.gridx = 1;
              c.gridy = k;
              c.gridwidth = 1;
              c.gridheight = 1;
              combo.addItem(" ");
              combo.setPreferredSize(prefSize);
              combo.setName(Integer.toString(attrib.getId()));
              combo.setSelectedItem(" ");
              attribPanel.add(combo, c);
            }
          }
          
          // 设置Table表格
          tableModel = new ClassifiTableModel(attributes);
          wsObjTable.setModel(tableModel);
          TableRowSorter sorter = new TableRowSorter(wsObjTable.getModel());  
          wsObjTable.setRowSorter(sorter);
          wsObjTable.updateUI();
          
        }else{
          attribPanel.removeAll();
        }
      //}
    }
    attribPanel.validate();
    attribPanel.updateUI();
    classifiObjTree.expandPath(selecPath);
  }

    /**
     * 根据查询条件查找ClassificationObject信息
   * @author Liugz
   * @create on 2009-3-6
   * This project for tc_communication.teamcenter2007
   */
  private void queryClassificationObject() {
    // 获取ClassificationClass的ClassId
    DefaultMutableTreeNode seleNode = (DefaultMutableTreeNode)classifiObjTree.getSelectionPath().getLastPathComponent();
    ClassifiClass clazz = (ClassifiClass)seleNode.getUserObject();
//    String type = clazz.getType();
//    int childcnt = clazz.getChildCount();
//    if((!"StorageClass".equalsIgnoreCase(type) && !"SubClass".equalsIgnoreCase(type)) || childcnt != 0){
//      JOptionPane.showMessageDialog(this, "请选择叶子节点进行查询！", "提示", JOptionPane.INFORMATION_MESSAGE);
//      return ;
//    }
    System.out.println("attribPanel.getComponentCount():"+attribPanel.getComponentCount());
    if(attribPanel.getComponentCount()==0){
      JOptionPane.showMessageDialog(frame, "无搜索条件，请选择其他节点", "提示", JOptionPane.INFORMATION_MESSAGE);
      return ;
    }
    // 收集页面上的信息，组成attributId=attributeValue的键值对
    Map<String, String> infos = new HashMap<String, String>();
    collectSearchInfo(attribPanel, infos);

    // 开始查询ClassificationObject
    List<ClassifiObject> clfObjs = cfop.queryClassificationObjects(clazz, infos);

    // 刷新表格
//    if(null != clfObjs && clfObjs.size() != 0){
//      tableModel.setClfObjs(clfObjs);
//    }
    tableModel.setClfObjs(clfObjs);
    wsObjTable.validate();
    TableRowSorter sorter = new TableRowSorter(wsObjTable.getModel());  
    wsObjTable.setRowSorter(sorter);
    wsObjTable.updateUI();
  }


  /**
   * @author Liugz
   * @create on 2009-3-6
   * This project for tc_communication.teamcenter2007
   */
  private void collectSearchInfo(JComponent comp, Map<String, String> infos) {
    Component[] comps = comp.getComponents();
    for(int i = 0; i < comps.length; i++){
      Component compon = comps[i];
      if(compon instanceof JTextComponent)
        infos.put(compon.getName(), ((JTextComponent)compon).getText());
      else if(compon instanceof JComboBox){
        Object seleObj = ((JComboBox)compon).getSelectedItem();
        if(seleObj instanceof LOVsValue){
          infos.put(compon.getName(), ((LOVsValue) seleObj).getDbValue());
        }
      }
    }
  }

  /**
   * 清除表格中的内容
   * @author Liugz
   * @create on 2009-3-8
   * This project for tc_communication.teamcenter2007
   */
  private void clearTablePanel() {
    // 清除表格中的内容
    tableModel.setClfObjs(null);
    wsObjTable.validate();
    wsObjTable.updateUI();
  }

  /**
   * 清空搜索条件对话框中的内容
   * @author Liugz
   * @create on 2009-3-8
   * This project for tc_communication.teamcenter2007
   */
  private void resetAttribPanel(){
    Component[] comps = attribPanel.getComponents();
    if(null == comps || comps.length == 0){
      return ;
    }
    for(Component comp : comps){
      if(comp instanceof JTextComponent){
        ((JTextComponent)comp).setText("");
      }
      if(comp instanceof JComboBox){
        ((JComboBox)comp).setSelectedItem(" ");
      }
    }
  }


  /**
   * 为ComboBox添加信息
   * @author Liugz
   * @create on 2009-3-7
   * This project for tc_communication.teamcenter2007
   * @param comp
   * @param items
   */
//  private void addItems(JComponent comp, Object[] items) {
//    if (null == items || items.length == 0) {
//      return;
//    }
//    if (comp instanceof JComboBox) {
//      // 先清空列表
//      // ((JComboBox)comp).removeAllItems();
//      for (Object item : items) {
//        ((JComboBox) comp).addItem(item);
//      }
//    }
//  }

  /**
   *
   * @author Liugz
   * @create on 2009-3-9
   * This project for CAD_Concrete
   * @param evt
   */
  private void cancelBtnActionPerformed(ActionEvent evt) {
    // 关闭按钮
    int r = JOptionPane.showConfirmDialog(this, "您尚未完成操作，确认退出？", "提示", JOptionPane.YES_NO_CANCEL_OPTION);
    if(r == JOptionPane.OK_OPTION){
      closeWindow();
    }
    else
      return ;
  }

  /**
   *
   * This project for CAD_Concrete
   * @param evt
   */
  private void okBtnActionPerformed(ActionEvent evt) {
    // 确定按钮
    int row = wsObjTable.getSelectedRow();
    
    String itemId = "";
    if(wsObjTable.getRowCount() != 0 && row != -1){
        for(int col = 0; col < wsObjTable.getColumnCount(); col++){
        String colName = wsObjTable.getColumnName(col);
        if("对象 ID".equals(colName)){
          String temp=(String)wsObjTable.getValueAt(row, col);
          if(temp.contains("/")){
            itemId = temp.split("/")[0];
          }else
          {
            itemId=temp;  
          }
          break ;
        }
      }
      // 查询选定的Item上的属性信息
      try {
        //ModelObject[] itemObj = new ObjectOperation().findObjectsBySavedQuery("零组件 ID", new String[]{itemId});
        WSObject[] itemObj=  tcop.queryObjectsBySavedQuery("零组件 ID", new String[]{itemId});
        
        WSObject itemRev=tcop.getItemRevision(itemObj[0], "Last");
        String partType=itemObj[0].getType();
        Map<String, String> propNames =new HashMap<String, String>();
        String itemName=itemRev.getName();
        propNames=itemProps.get(partType);
        WSObject wsObj=tcop.getItemRevisionInfo(itemRev, propNames);
        Map<String, String> attrib = wsObj.getAttributes();
        
        boolean okflag=true;
        if(attrib.get("材料种类").equals("金属材料")){
          int ok=JOptionPane.showConfirmDialog(this, "您所选为金属材料，是否填写材料规格", "提示", JOptionPane.YES_NO_OPTION);
          if(ok!=0){
            okflag=false;
          }
        }
        
        backfillCADDrawing(attrib,itemId,itemName,"零部件",okflag);
      } catch (TCOperationException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
      }
    }
    else {
      JOptionPane.showMessageDialog(this, "您尚未选择要返回的数据，请选择要返回的数据！", "提示", JOptionPane.INFORMATION_MESSAGE);
      return ;
    }
  
    frame.dispose();

  }

  /**
   * 将对话框信息反填回CAD图纸
   * @author Liugz
   * @create on 2009-2-25
   * This project for CAD_Concrete
   * @return
   */
  private void backfillCADDrawing(Map<String, String> infos,String id,String itemname,String type, boolean okflag) {
        // 修改请求中的信息
    
    out.setFuncID("QueryMat");
    out.setResult("true");
    out.setDesc("Backfill CAD Drawing.");
    Element object2 = out.getObjectElement();
    //object2.addAttribute("type", type);
    Element props = object2.addElement("properties");

    Element root = this.requestBody;
    
    Element object = root.element("body");//.element("object");
    
    String key="";
    Set<String> keys=infos.keySet();
    Object[] ks=keys.toArray();
    Element pro=props.addElement("property");
    pro.addAttribute("name","材料编码");
    pro.addAttribute("value",id );
    Element proname=props.addElement("property");
    if(infos.get("材料简称").equals("")){
      
      proname.addAttribute("name","材料名称");
      proname.addAttribute("value",itemname);
    }else
    {
      proname.addAttribute("name","材料名称");
      proname.addAttribute("value",infos.get("材料简称"));
    }
    for(int i=0;i<ks.length;i++){
      Element pro1=props.addElement("property");
      String name=ks[i].toString();
      if(name.equals("重量")){
        name="质量";
      }
      pro1.addAttribute("name",name);
      pro1.addAttribute("value",infos.get(ks[i].toString()) );
    }
    String matdown=infos.get("材质标准");
    String matGG=infos.get("材料规格");
    String matg1=infos.get("材质规格");
    String matstarded=infos.get("材料标准");
    String matUp=matg1+" "+matGG+" "+matstarded;
    if(!okflag){
      matUp=matg1+" "+matstarded;
    }
    if(infos.get("材料种类").equals("非金属材料")){
      matdown=infos.get("材料标准");
      matUp=matGG;
    }else if(infos.get("材料种类").equals("材质")){
      matUp=matg1;
    }
    Element promatup=props.addElement("property");
    promatup.addAttribute("name","材料上标");
    promatup.addAttribute("value",matUp);
      
    Element promatdown=props.addElement("property");
    promatdown.addAttribute("name","材料下标");
    promatdown.addAttribute("value",matdown);
    
    try {
      // 将CAD信息打印出来
      out.sendResultToUI();
    } catch (IOException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
  }


  /**
   * 选择树节点时的操作
   * @author Liugz
   * @create on 2009-3-12
   * This project for CAD_Concrete
   * @param event
   */
  protected void treeSelectionAction(TreeSelectionEvent event) {
//    stateDlg = new StateDialog(frame, false, "正在载入内容，请稍候……");
    Thread thread = new Thread(new Runnable(){

      public void run() {
        if(waitDlg != null)
          waitDlg.dispose();

        waitDlg = new WaitDialog(frame, false);
        frame.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        findSubNodes();
        frame.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        waitDlg.dispose();
      }

    });
    thread.start();
  }

  //ClassificationOperation cfop = new ClassificationOperation();
  TCClassificationOperation  cfop = new TCClassificationOperation();
  DefaultMutableTreeNode root;
  DefaultMutableTreeNode root1;
  DefaultMutableTreeNode root2;
  DefaultTreeModel treeModel;
  ClassifiTableModel tableModel;
  WorkspaceTableRender tableRender;
  Dimension prefSize = new Dimension(200, 20);
  private static Map<String, Map<String, String>> itemProps = ParseRequestXML.getTCObjectProps();
   
    private Element requestBody;
    private AdaptorWriter out;
    private JFrame frame;
    private StateDialog stateDlg;
    private WaitDialog waitDlg;
    public QueryMatPane(Element requestBody, AdaptorWriter out, JFrame frame) {
      this.frame = frame;
      this.requestBody = requestBody;
      this.out = out;
      initComponents();
      initDialog();
    }

  /**
   * @return the requestBody
   */
  public Element getRequestBody() {
    return requestBody;
  }

  /**
   * @param requestBody the requestBody to set
   */
  public void setRequestBody(Element requestBody) {
    this.requestBody = requestBody;
  }

  /**
   * @return the out
   */
  public AdaptorWriter getOut() {
    return out;
  }

  /**
   * @param out the out to set
   */
  public  void setOut(AdaptorWriter out) {
    this.out = out;
  }

}
